version: "3.8"

services:
  web:
    build: .
    volumes:
      - ./app:/app/app
    ports:
      - "8081:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        limits:
          memory: "200M"
