apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lector-binding
  namespace: default
subjects:
  - kind: User
    name: juan
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: lector-pods
  apiGroup: rbac.authorization.k8s.io
