# Lab 4: emptyDir entre contenedores
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "echo 'Hola desde writer' > /shared/data.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
    - name: reader
      image: busybox
      command: ["sh", "-c", "sleep 5 && cat /shared/data.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
  volumes:
    - name: shared-data
      emptyDir: {}