version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8100:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app