apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wordpress
type: Opaque
stringData:
  wordpress-password: wp123.
  wordpress-username: admin
  mariadb-root-password: wp123.
  mariadb-password: wp123.
