apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-db
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: wordpress-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: mariadb-password
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svcbd
  namespace: wordpress
spec:
  selector:
    app: wp-db
  ports:
    - port: 3306
      targetPort: 3306